In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("../data/heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.shape

(918, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [6]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [7]:
df.columns.tolist()

['Age',
 'Sex',
 'ChestPainType',
 'RestingBP',
 'Cholesterol',
 'FastingBS',
 'RestingECG',
 'MaxHR',
 'ExerciseAngina',
 'Oldpeak',
 'ST_Slope',
 'HeartDisease']

In [8]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [9]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
913    False
914    False
915    False
916    False
917    False
Length: 918, dtype: bool

In [10]:
(df['Cholesterol']==0).sum()

172

In [11]:
print(df.groupby(df['Cholesterol'].eq(0))['HeartDisease'].value_counts(normalize=True))

Cholesterol  HeartDisease
False        0               0.522788
             1               0.477212
True         1               0.883721
             0               0.116279
Name: proportion, dtype: float64

In [12]:
print(df.groupby(
    df['Cholesterol'].eq(0)
).agg(
    count=('Cholesterol', 'size'),
    heart_disease_rate=('HeartDisease','mean'),
    avg_age=('Age','mean')
)
)

             count  heart_disease_rate    avg_age
Cholesterol
False          746            0.477212  52.882038
True           172            0.883721  56.238372

In [13]:
pd.crosstab(
    df['Cholesterol'].eq(0),
    df['HeartDisease']
)

HeartDisease    0    1
Cholesterol
False         390  356
True           20  152

In [14]:
print(
    df.groupby(df["Cholesterol"].eq(0))[
        ["Age", "RestingBP", "MaxHR", "Oldpeak"]
    ].mean()
)

                   Age   RestingBP       MaxHR   Oldpeak
Cholesterol
False        52.882038  133.022788  140.226542  0.901609
True         56.238372  129.680233  121.988372  0.825581

In [15]:
print(
    df.groupby("HeartDisease")["Cholesterol"]
      .apply(lambda x: (x == 0).mean())
)

HeartDisease
0    0.048780
1    0.299213
Name: Cholesterol, dtype: float64

In [16]:
for col in ["Age","Sex","ChestPainType","ExerciseAngina","ST_Slope"]:
    print("----------------------------")
    print(
        pd.crosstab(
            df['Cholesterol'].eq(0),
            df[col],
            normalize="index"
        ).round(3)*100
    )

----------------------------
Age           28   29   30   31   32   33   34   35   36   37  ...   68   69  \
Cholesterol                                                    ...
False        0.1  0.4  0.1  0.3  0.5  0.3  0.8  1.3  0.7  1.5  ...  0.9  1.2
True         0.0  0.0  0.0  0.0  0.6  0.0  0.6  0.6  0.6  0.0  ...  1.7  2.3

Age           70   71   72   73   74   75   76   77
Cholesterol
False        0.7  0.7  0.4  0.0  0.7  0.4  0.3  0.3
True         1.2  0.0  0.6  0.6  1.2  0.0  0.0  0.0

[2 rows x 50 columns]
----------------------------
Sex             F     M
Cholesterol
False        24.4  75.6
True          6.4  93.6
----------------------------
ChestPainType   ASY   ATA   NAP   TA
Cholesterol
False          49.6  22.3  22.7  5.5
True           73.3   4.1  19.8  2.9
----------------------------
ExerciseAngina     N     Y
Cholesterol
False           61.5  38.5
True            51.2  48.8
----------------------------
ST_Slope     Down  Flat    Up
Cholesterol
False         5.8  47.5  46.8
True         11.6  61.6  26.7

In [17]:
pd.crosstab(
    df["Cholesterol"].eq(0),
    df["ExerciseAngina"],
    normalize="index"
).round(3) * 100

ExerciseAngina     N     Y
Cholesterol
False           61.5  38.5
True            51.2  48.8

In [18]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object